version: '3.8'
services:
  hs-app-1:
    image: oboznyi/hs-app:1
    ports:
      - 8080:8080
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3307

  hs-app-2:
    image: oboznyi/hs-app:1
    ports:
      - 8082:8080
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3307

  hs-app-3:
    image: oboznyi/hs-app:1
    ports:
      - 8083:8080
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3307

  hs-lb:
    image: oboznyi/hs-lb:1
    ports:
      - 5000:8080
    environment:
      BACKENDS: "http://host.docker.internal:8080,http://host.docker.internal:8082,http://host.docker.internal:8083"

  mysql:
    image: mysql:8
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3307:3306

volumes:
  mysql:
